### ISSUE TITLE
undefined is not a function 

### ISSUE THREAD

**Issue by shreyasBhargava** [marcobarcelos/node-msmq#1]
1. when i "Try it out" online from this link https://tonicdev.com/npm/node-msmq
then also it is giving error "TypeError: undefined is not a function" 

2. when i install this npm in my project and just wrote 

const msmq = require('node-msmq');

it is giving me error 

\node_modules\node-msmq\dist\proxy.js:24
return _edge2.default.func(Object.assign({}, baseOptions, { methodName: metho
	                                  ^
TypeError: undefined is not a function

**Comment by marcobarcelos** [comment]
Hi @shreyasBhargava , what version of Node.js are you using?
Tonic dev runs on Node v0.12.14, which doesn't support Object.assign().
I'll be adding a polyfill for supporting this method in older versions of node.

**Comment by marcobarcelos** [comment]
Just included babel-transform-runtime plugin (https://github.com/marcobarcelos/node-msmq/commit/3f73c08d454fd84935b6d55d9a5397cfd66636b6), now working with older versions of node.js.
Please upgrade node-msmq to version 0.1.3.

**Comment by shreyasBhargava** [comment]
thank you
